### PR TITLE
added rockspec

### PR DESCRIPTION
**Pull request by jamesalbert**
Hi @kikito, anim8's been a big help making animations really easy. I'm submitting a rockspec for it to make it a little easier for people to download and use :)

### CODE REVIEW

**Comment by jamesalbert** [comment]
I've heard of verbose reporting, but this is just ridiculous 😛

**Comment by jamesalbert** [comment]
Awesome man, thanks for the tips. I'm not too familiar with luarocks 😛no worries on the coveralls reports, I've had it happen to me a bunch

**Comment by jamesalbert** [comment]
@kikito I was scrolling past my open PRs and found this 😮 

I think it's a [matter of preference](https://github.com/luarocks/luarocks/wiki/Rockspec-format#build-rules). I can change it to that if needed.

**Comment by kikito** [comment]
Well, guess what. 4 years have passed since I last looked at this..

I decided to close this one. I think if people want to use anim8 in LÖVE they'd better download the files. Having multiple ways of doing things will confound newcomers.

(also: spec files should't be included in rockspecs).

I'm grateful for the PR though. Have a good day!

**Pull request closed without merging**
